# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bryan King
email: bpking15@gmail.com
description: Bryan King is a web developer and designer living in Rochester, MI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kingbryan.me" # the base hostname & protocol for your site
twitter_username: kingbryandotme
github_username:  kingbryan

# Build settings
markdown: kramdown
